//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public int article_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string body { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
