//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTable
    {
        public int id { get; set; }
        public string namefile { get; set; }
        public string path { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public string name { get; set; }
    }
}
