//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amphure> Amphures { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<Geography> Geographies { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Tumbon> Tumbons { get; set; }
        public virtual DbSet<FileTable> FileTables { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
    }
}
